language: node_js

env:
    global:
        - PATH=$HOME/.local/bin:$PATH
        
before_install:
    - pip install --user awscli nodejs

jobs:
    include:
        - stage: build
        script:
            - npm -v
            - npm run build
        - stage: push
        script:
            - cd dist
            - aws s3 sync ChatTool s3://app-chat-7/