language: node_js
node_js:
  - "10"
sudo: true
dist: trusty

branches:
  only:
    - master
       
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
        
before_install:
  - pip install --user awscli

jobs:
  include:
    - stage: build
      script:
        - npm -v
        - npm run build
        - cd dist
#        - aws s3 sync ChatTool s3://app-chat-7/
